--DATABASE
--Create database [Medical] - Simple Mode/v150
--Single file as this is a tiny database currently

USE Master;
GO

CREATE DATABASE [Medical]
  CONTAINMENT = NONE
  ON  PRIMARY 
(NAME = N'Medical', 
  FILENAME = N'D:\SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Medical.mdf' , 
  SIZE = 819200KB , 
  FILEGROWTH = 65536KB)
  LOG ON 
(NAME = N'Medical_log', 
  FILENAME = N'D:\SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Log\Medical_log.ldf' , 
  SIZE = 81920KB , 
  FILEGROWTH = 65536KB);
GO

ALTER DATABASE [Medical] SET COMPATIBILITY_LEVEL = 150;
ALTER DATABASE [Medical] SET ANSI_NULL_DEFAULT OFF;
ALTER DATABASE [Medical] SET ANSI_NULLS OFF;
ALTER DATABASE [Medical] SET ANSI_PADDING OFF;
ALTER DATABASE [Medical] SET ANSI_WARNINGS OFF;
ALTER DATABASE [Medical] SET ARITHABORT OFF;
ALTER DATABASE [Medical] SET AUTO_CLOSE OFF;
ALTER DATABASE [Medical] SET AUTO_SHRINK OFF;
ALTER DATABASE [Medical] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF);
ALTER DATABASE [Medical] SET AUTO_UPDATE_STATISTICS ON;
ALTER DATABASE [Medical] SET CURSOR_CLOSE_ON_COMMIT OFF;
ALTER DATABASE [Medical] SET CURSOR_DEFAULT  GLOBAL;
ALTER DATABASE [Medical] SET CONCAT_NULL_YIELDS_NULL OFF;
ALTER DATABASE [Medical] SET NUMERIC_ROUNDABORT OFF;
ALTER DATABASE [Medical] SET QUOTED_IDENTIFIER OFF;
ALTER DATABASE [Medical] SET RECURSIVE_TRIGGERS OFF;
ALTER DATABASE [Medical] SET DISABLE_BROKER;
ALTER DATABASE [Medical] SET AUTO_UPDATE_STATISTICS_ASYNC OFF;
ALTER DATABASE [Medical] SET DATE_CORRELATION_OPTIMIZATION OFF;
ALTER DATABASE [Medical] SET PARAMETERIZATION SIMPLE;
ALTER DATABASE [Medical] SET READ_COMMITTED_SNAPSHOT OFF;
ALTER DATABASE [Medical] SET READ_WRITE;
ALTER DATABASE [Medical] SET RECOVERY SIMPLE;
ALTER DATABASE [Medical] SET MULTI_USER;
ALTER DATABASE [Medical] SET PAGE_VERIFY CHECKSUM;
ALTER DATABASE [Medical] SET TARGET_RECOVERY_TIME = 60 SECONDS;
ALTER DATABASE [Medical] SET DELAYED_DURABILITY = DISABLED;
GO

USE [Medical]
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO

USE [Medical]
GO
IF NOT EXISTS (
  SELECT [name] 
  FROM sys.filegroups 
  WHERE is_default=1 AND [name] = N'PRIMARY') 
  ALTER DATABASE [Medical] MODIFY FILEGROUP [PRIMARY] DEFAULT;
GO
