USE Medical;
GO

DROP TABLE IF EXISTS dbo.tds_colors;
GO

CREATE TABLE dbo.tds_colors(
  id INT IDENTITY(1,1) NOT NULL,
  isActive NVARCHAR(8) NOT NULL,
  colorAlias NVARCHAR(60) NOT NULL,
  colorName NVARCHAR(60) NULL,
  valueHex NVARCHAR(24) NULL,
  valueHSB NVARCHAR(24) NULL,
  valueHSL NVARCHAR(24) NULL,
  valueRGB NVARCHAR(24) NULL,
  valueCYMK NVARCHAR(24) NULL,
  valueLAB NVARCHAR(24) NULL,
  valueRAL NVARCHAR(24) NULL,
  valueHKS NVARCHAR(24) NULL,
  valueCOPIC NVARCHAR(60) NULL,
  valuePRISMA NVARCHAR(60) NULL,
  valueLONG BIGINT NULL,
  shortDescription NVARCHAR(255) NULL,
  dateCreated DATETIME NOT NULL,
  dateModified DATETIME NOT NULL,
  createdBY NVARCHAR(60) NOT NULL,
  modifiedBY NVARCHAR(60) NOT NULL
);
GO